fullnameOverride: argocd

configs:
  cm:
    kustomize.enabled: true
    jsonnet.enabled: true
    helm.enabled: true

    ui.bannercontent: |
      Hello there!<hr>
      sadf<br />
      safd<br />
    ui.bannerurl: "https://argoproj.github.io"
    ui.bannerpermanent: "true"
    ui.bannerposition: "top"

    timeout.reconciliation: 1m

    resource.ignoreResourceUpdatesEnabled: "true"
    #resource.customizations.ignoreResourceUpdates.all: |
    #  jsonPointers:
    #    - /metadata/resourceVersion

    #resource.customizations.ignoreResourceUpdates.argoproj.io_Application: |
    #  jsonPointers:
    #    - /status

  params:
    server.disable.auth: true
    server.insecure: true
    server.log.format: "json"
    server.log.level: "info"
    server.oidc.cache.expiration: "1m"
    server.default.cache.expiration: "1m"
    server.login.attempts.expiration: "1m"
    server.app.state.cache.expiration: "1m"
    server.connection.status.cache.expiration: "1m"

    reposerver.parallelism.limit: 0
    reposerver.log.format: "json"
    reposerver.log.level: "info"
    reposerver.repo.cache.expiration: "1m"
    reposerver.default.cache.expiration: "1m"
    reposerver.enable.git.submodule: "false"

    controller.sharding.algorithm: "round-robin"
    controller.resource.health.persist: "false"
    controller.log.format: "json"
    controller.log.level: "info"
    controller.metrics.cache.expiration: "1m"
    controller.app.state.cache.expiration: "1m"
    controller.default.cache.expiration: "1m"

    applicationsetcontroller.log.format: "json"
    applicationsetcontroller.log.level: "info"
    applicationsetcontroller.enable.git.submodule: "false"

    notificationscontroller.log.format: "json"
    notificationscontroller.log.level: "info"

server:
  replicas: 2

  service:
    type: LoadBalancer
    servicePortHttp: 8080
    servicePortHttps: 8443

repoServer:
  replicas: 2

applicationSet:
  replicas: 3

controller:
  replicas: 2

redis:
  enabled: false

redis-ha:
  enabled: true

  replicas: 1

  haproxy:
    replicas: 1