fullnameOverride: argocd

configs:
  params:
    server.disable.auth: true
    server.insecure: true
    
    reposerver.parallelism.limit: 0

server:
  replicas: 1

  service:
    type: LoadBalancer
    servicePortHttp: 8080
    servicePortHttps: 8443

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

controller:
  replicas: 1

redis:
  enabled: false

redis-ha:
  enabled: true

  replicas: 1

  haproxy:
    replicas: 1