fullnameOverride: argocd

configs:
  params:
    server.disable.auth: true
    server.insecure: true

    reposerver.parallelism.limit: 0
    reposerver.repo.cache.expiration: "5s"
    reposerver.default.cache.expiration: "5s"

    controller.app.state.cache.expiration: "5s"
    controller.default.cache.expiration: "5s"

    server.oidc.cache.expiration: "5s"
    server.app.state.cache.expiration: "5s"
    server.default.cache.expiration: "5s"

server:
  replicas: 1

  service:
    type: LoadBalancer
    servicePortHttp: 8080
    servicePortHttps: 8443

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

controller:
  replicas: 1

redis:
  enabled: false

redis-ha:
  enabled: true

  replicas: 1

  haproxy:
    replicas: 1