apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd-system
spec:
  project: argo-workflows-system
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: argo-workflows
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.25.1
      helm:
        releaseName: argo-workflows
        valueFiles:
          - $argocd-self/base/stacks/argo-workflows-stack/workflows/values.yaml
