apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/istio-metrics/jaeger
  - ../../../base/istio-metrics/elasticsearch
  - ../../../base/istio-metrics/kibana
  - ../../../base/istio-metrics/kiali