auth:
  strategy: anonymous

deployment:
  service_type: LoadBalancer

external_services:
  grafana:
    enabled: true
    in_cluster_url: http://grafana.metrics-system:8080

#  istio:
#    component_status:
#      components: []
#      enabled: true

  prometheus:
    enabled: true
    url: http://prometheus-server.metrics-system:8080

  tracing:
    enabled: true
    in_cluster_url: http://jaeger-query.istio-tracing-system:16685

istio_namespace: istio-system

kiali_feature_flags:
  istio_upgrade_action: true

server:
  port: 8080