apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd-system
spec:
  project: metrics-system
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.46.1
      helm:
        releaseName: grafana
        valueFiles:
          - $argocd-self/base/stacks/metrics/grafana/values.yaml