apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-metallb
  namespace: argocd-system
spec:
  project: metallb-system
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.13.9
      helm:
        releaseName: metallb
        valueFiles:
          - $argocd-self/base/generic/metallb/values.yaml
  ignoreDifferences:
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle