apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-prometheus-operator-admission-webhook
  namespace: argocd-system
spec:
  project: metrics-system
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: prometheus-operator-admission-webhook
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 0.8.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $argocd-self/base/stacks/metrics/prometheus-operator-admission-webhook/values.yaml