fullnameOverride: argocd

configs:
  repositories:
    seemscloud-app-argocd-self:
      url: https://github.com/seemscloud/helm-argocd-self.git
      name: "[SeemsCloud][App] Argo Self"
      type: git
      insecure: "true"
    ext-helm-argoproj:
      url: https://argoproj.github.io/argo-helm
      name: "[Ext][Helm] ArgoProj"
      type: helm
      insecure: "true"
    ext-helm-bitnami:
      url: https://charts.bitnami.com/bitnami
      name: "[Ext][Helm] Bitnami"
      type: helm
      insecure: "true"
    ext-helm-prometheus-community:
      url: https://prometheus-community.github.io/helm-charts
      name: "[Ext][Helm] Prometheus Community"
      type: helm
      insecure: "true"
    ext-helm-grafana:
      url: https://grafana.github.io/helm-charts
      name: "[Ext][Helm] Grafana"
      type: helm
      insecure: "true"
    ext-helm-kiali:
      url: https://kiali.org/helm-charts
      name: "[Ext][Helm] Kiali"
      type: helm
      insecure: "true"
    ext-helm-jaegertracing:
      url: https://jaegertracing.github.io/helm-charts
      name: "[Ext][Helm] Jaeger Tracing"
      type: helm
      insecure: "true"
    ext-helm-redpanda:
      url: https://charts.redpanda.com
      name: "[Ext][Helm] Redpanda"
      type: helm
      insecure: "true"
    ext-helm-stakater:
      url: https://stakater.github.io/stakater-charts
      name: "[Ext][Helm] Stakater"
      type: helm
      insecure: "true"
    ext-helm-hashicorp:
      url: https://helm.releases.hashicorp.com
      name: "[Ext][Helm] HashiCorp"
      type: helm
      insecure: "true"
    ext-helm-jenkins:
      url: https://charts.jenkins.io
      name: "[Ext][Helm] Jenkins"
      type: helm
      insecure: "true"
    ext-helm-minio:
      url: https://charts.min.io
      name: "[Ext][Helm] MinIO"
      type: helm
      insecure: "true"
    ext-helm-jetstack:
      url: https://charts.jetstack.io
      name: "[Ext][Helm] JetStack"
      type: helm
      insecure: "true"
    ext-helm-metallb:
      url: https://metallb.github.io/metallb
      name: "[Ext][Helm] MetalLB"
      type: helm
      insecure: "true"
    ext-helm-kedacore:
      url: https://kedacore.github.io/charts
      name: "[Ext][Helm] KEDA"
      type: helm
      insecure: "true"
    ext-helm-elastic:
      url: https://helm.elastic.co
      name: "[Ext][Helm] Elastic"
      type: helm
      insecure: "true"
    ext-helm-istio:
      url: https://istio-release.storage.googleapis.com/charts
      name: "[Ext][Helm] Istio"
      type: helm
      insecure: "true"
    ext-helm-crossplane:
      url: https://charts.crossplane.io/stable
      name: "[Ext][Helm] Crossplane"
      type: helm
      insecure: "true"
    ext-helm-kyverno:
      url: https://kyverno.github.io/kyverno/
      name: "[Ext][Helm] Kyverno"
      type: helm
      insecure: "true"
    ext-helm-fluent:
      url: https://fluent.github.io/helm-charts
      name: "[Ext][Helm] Fluent"
      type: helm
      insecure: "true"

  cm:
    kustomize.enabled: true
    jsonnet.enabled: true
    helm.enabled: true

    ui.bannercontent: |
      Hello there!<hr>
      sadf<br />
      safd<br />
    ui.bannerurl: "https://argoproj.github.io"
    ui.bannerpermanent: "true"
    ui.bannerposition: "top"

    timeout.reconciliation: 1m

    resource.ignoreResourceUpdatesEnabled: "true"
    #resource.customizations.ignoreResourceUpdates.all: |
    #  jsonPointers:
    #    - /metadata/resourceVersion

    #resource.customizations.ignoreResourceUpdates.argoproj.io_Application: |
    #  jsonPointers:
    #    - /status

  params:
    server.disable.auth: true
    server.insecure: true
    server.log.format: "json"
    server.log.level: "info"
    server.oidc.cache.expiration: "1m"
    server.default.cache.expiration: "1m"
    server.login.attempts.expiration: "1m"
    server.app.state.cache.expiration: "1m"
    server.connection.status.cache.expiration: "1m"

    reposerver.parallelism.limit: 0
    reposerver.log.format: "json"
    reposerver.log.level: "info"
    reposerver.repo.cache.expiration: "1m"
    reposerver.default.cache.expiration: "1m"
    reposerver.enable.git.submodule: "false"

    controller.sharding.algorithm: "round-robin"
    controller.resource.health.persist: "false"
    controller.log.format: "json"
    controller.log.level: "info"
    controller.metrics.cache.expiration: "1m"
    controller.app.state.cache.expiration: "1m"
    controller.default.cache.expiration: "1m"

    applicationsetcontroller.log.format: "json"
    applicationsetcontroller.log.level: "info"
    applicationsetcontroller.enable.git.submodule: "false"

    notificationscontroller.log.format: "json"
    notificationscontroller.log.level: "info"

server:
  replicas: 2

  service:
    type: LoadBalancer
    servicePortHttp: 8080
    servicePortHttps: 8443

repoServer:
  replicas: 2

applicationSet:
  replicas: 3

controller:
  replicas: 2

redis:
  enabled: false

redis-ha:
  enabled: true

  replicas: 2

  haproxy:
    replicas: 2