fullnameOverride: argocd

configs:
  repositories:
    seemscloud-app-argocd-self:
      url: https://github.com/seemscloud/helm-argocd-self.git
      name: "[SeemsCloud][App] Argo Self"
      type: git
      insecure: "true"
    argoproj-helm-charts:
      url: https://argoproj.github.io/argo-helm
      name: "[Ext][ArgoProj] Helm Charts"
      type: helm
      insecure: "true"
    bitnami-helm-charts:
      url: https://charts.bitnami.com/bitnami
      name: "[Ext][Bitnami] Helm Charts"
      type: helm
      insecure: "true"
    prometheus-community-helm-charts:
      url: https://prometheus-community.github.io/helm-charts
      name: "[Ext][Prometheus Community] Helm Charts"
      type: helm
      insecure: "true"
    grafana-helm-charts:
      url: https://grafana.github.io/helm-charts
      name: "[Ext][Grafana] Helm Charts"
      type: helm
      insecure: "true"
    kiali-helm-charts:
      url: https://kiali.org/helm-charts
      name: "[Ext][Kiali] Helm Charts"
      type: helm
      insecure: "true"
    jaegertracing-helm-charts:
      url: https://jaegertracing.github.io/helm-charts
      name: "[Ext][Jaeger Tracing] Helm Charts"
      type: helm
      insecure: "true"
    redpanda-helm-charts:
      url: https://charts.redpanda.com
      name: "[Ext][Redpanda] Helm Charts"
      type: helm
      insecure: "true"
    kube-logging-helm-charts:
      url: https://kube-logging.github.io/helm-charts
      name: "[Ext][Kube Logging] Helm Charts"
      type: helm
      insecure: "true"
    stakater-helm-charts:
      url: https://stakater.github.io/stakater-charts
      name: "[Ext][Stakater] Helm Charts"
      type: helm
      insecure: "true"
    hashicorp-helm-charts:
      url: https://helm.releases.hashicorp.com
      name: "[Ext][HashiCorp] Helm Charts"
      type: helm
      insecure: "true"
    jenkins-helm-charts:
      url: https://charts.jenkins.io
      name: "[Ext][Jenkins] Helm Charts"
      type: helm
      insecure: "true"
    min-io-helm-charts:
      url: https://charts.min.io
      name: "[Ext][MinIO] Helm Charts"
      type: helm
      insecure: "true"
    jetstack-helm-charts:
      url: https://charts.jetstack.io
      name: "[Ext][JetStack] Helm Charts"
      type: helm
      insecure: "true"
    metallb-helm-charts:
      url: https://metallb.github.io/metallb
      name: "[Ext][MetaLB] Helm Charts"
      type: helm
      insecure: "true"
    kedacore-helm-charts:
      url: https://kedacore.github.io/charts
      name: "[Ext][KEDA] Helm Charts"
      type: helm
      insecure: "true"
    elastic-helm-charts:
      url: https://helm.elastic.co
      name: "[Ext][Elastic] Helm Charts"
      type: helm
      insecure: "true"
    istio-helm-charts:
      url: https://istio-release.storage.googleapis.com/charts
      name: "[Ext][Istio] Helm Charts"
      type: helm
      insecure: "true"
    crossplane-helm-charts:
      url: https://charts.crossplane.io/stable
      name: "[Ext][Crossplane] Helm Charts"
      type: helm
      insecure: "true"
    kyverno-helm-charts:
      url: https://kyverno.github.io/kyverno/
      name: "[Ext][Kyverno] Helm Charts"
      type: helm
      insecure: "true"
    fluent-helm-charts:
      url: https://fluent.github.io/helm-charts
      name: "[Ext][Fluent] Helm Charts"
      type: helm
      insecure: "true"

      #
  cm:
    kustomize.enabled: true
    jsonnet.enabled: true
    helm.enabled: true

    ui.bannercontent: |
      Hello there!<hr>
      sadf<br />
      safd<br />
    ui.bannerurl: "https://argoproj.github.io"
    ui.bannerpermanent: "true"
    ui.bannerposition: "top"

    timeout.reconciliation: 1m

    resource.ignoreResourceUpdatesEnabled: "true"
    #resource.customizations.ignoreResourceUpdates.all: |
    #  jsonPointers:
    #    - /metadata/resourceVersion

    #resource.customizations.ignoreResourceUpdates.argoproj.io_Application: |
    #  jsonPointers:
    #    - /status

  params:
    server.disable.auth: true
    server.insecure: true
    server.log.format: "json"
    server.log.level: "info"
    server.oidc.cache.expiration: "1m"
    server.default.cache.expiration: "1m"
    server.login.attempts.expiration: "1m"
    server.app.state.cache.expiration: "1m"
    server.connection.status.cache.expiration: "1m"

    reposerver.parallelism.limit: 0
    reposerver.log.format: "json"
    reposerver.log.level: "info"
    reposerver.repo.cache.expiration: "1m"
    reposerver.default.cache.expiration: "1m"
    reposerver.enable.git.submodule: "false"

    controller.sharding.algorithm: "round-robin"
    controller.resource.health.persist: "false"
    controller.log.format: "json"
    controller.log.level: "info"
    controller.metrics.cache.expiration: "1m"
    controller.app.state.cache.expiration: "1m"
    controller.default.cache.expiration: "1m"

    applicationsetcontroller.log.format: "json"
    applicationsetcontroller.log.level: "info"
    applicationsetcontroller.enable.git.submodule: "false"

    notificationscontroller.log.format: "json"
    notificationscontroller.log.level: "info"

server:
  replicas: 2

  service:
    type: LoadBalancer
    servicePortHttp: 8080
    servicePortHttps: 8443

repoServer:
  replicas: 2

applicationSet:
  replicas: 3

controller:
  replicas: 2

redis:
  enabled: false

redis-ha:
  enabled: true

  replicas: 2

  haproxy:
    replicas: 2