apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-gateway-green
  namespace: argocd-system
spec:
  project: istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingressgateway-green-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: gateway
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.19.3
      helm:
        releaseName: ingress-gateway-green
        valueFiles:
          - $argocd-self/base/stacks/istio/istio/ingress-gateway/values.yaml
          - $argocd-self/base/stacks/istio/istio/ingress-gateway/values-green.yaml
  ignoreDifferences:
    - kind: ValidatingWebhookConfiguration
      group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks/0/failurePolicy
