apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd-system
spec:
  project: metrics-system
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-system
  info:
    - name: argocd.seems.cloud/domain
      value: tools
    - name: argocd.seems.cloud/team
      value: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions: [ ]
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 19.0.1
      helm:
        releaseName: prometheus
        valueFiles:
          - $argocd-self/base/prometheus/values.yaml
