apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-istiod-blue
  namespace: argocd-system
spec:
  project: istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.17.1
      helm:
        releaseName: istiod
        valueFiles:
          - $argocd-self/base/istio-istiod/values.yaml
  ignoreDifferences:
    - kind: ValidatingWebhookConfiguration
      group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks/0/failurePolicy