fullnameOverride: rabbitmq

replicaCount: 3

service:
  type: LoadBalancer

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

persistence:
  enabled: false

auth:
  username: user
  password: "Admin101123"

serviceAccount:
  create: true