apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-prometheus-operator
  namespace: argocd-system
spec:
  project: metrics-system
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: prometheus-operator
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 9.3.2
      helm:
        releaseName: prometheus-operator
        valueFiles:
          - $argocd-self/base/stacks/metrics/prometheus-operator/values.yaml