apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-stack/
  - ../../base/metallb
  - ../../base/cert-manager
  #  - queues-stack/
  - metrics-stack/
  - istio-stack/
  - argo-workflows-stack/
  - others/