apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/argocd
  - ../../base/argocd-apps
  - ../../base/argocd-self
  - ../../base/metrics-prometheus
  - ../../base/metrics-grafana
  - ../../base/istio-base
  - ../../base/istio-istiod
  - ../../base/istio-ingress-gateway
  - ../../base/istio-jaeger
  - ../../base/istio-elasticsearch
  - ../../base/istio-kibana
  - ../../base/argo-events
  - ../../base/argo-minio
  - ../../base/argo-workflows
  - ../../base/metallb
  - ../../base/cert-manager
  - ../../base/istio-kiali
  - ../../base/keda
  - ../../base/logging-redpanda
  - ../../base/logging-operator
  - ../../base/logging-operator-logging

patches:
##########################################################################################
#                                  _____  _____
#       /\                        / ____||  __ \
#      /  \    _ __  __ _   ___  | |     | |  | |
#     / /\ \  | '__|/ _` | / _ \ | |     | |  | |
#    / ____ \ | |  | (_| || (_) || |____ | |__| |
#   /_/    \_\|_|   \__, | \___/  \_____||_____/
#                    __/ |
#                   |___/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argocd/values.yaml
          - $argocd-self/overlays/seemscloud/values/argocd/values.yaml
    target:
      kind: Application
      name: argocd
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argocd-apps/values.yaml
          - $argocd-self/overlays/seemscloud/values/argocd-apps/values.yaml
    target:
      kind: Application
      name: argocd-apps
##########################################################################################
#    __  __        _          _
#   |  \/  |      | |        (_)
#   | \  / |  ___ | |_  _ __  _   ___  ___
#   | |\/| | / _ \| __|| '__|| | / __|/ __|
#   | |  | ||  __/| |_ | |   | || (__ \__ \
#   |_|  |_| \___| \__||_|   |_| \___||___/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/metrics-prometheus/values.yaml
          - $argocd-self/overlays/seemscloud/values/metrics-prometheus/values.yaml
    target:
      kind: Application
      name: metrics-prometheus
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/metrics-grafana/values.yaml
          - $argocd-self/overlays/seemscloud/values/metrics-grafana/values.yaml
    target:
      kind: Application
      name: metrics-grafana
##########################################################################################
#     _____             _     __  __
#    / ____|           | |   |  \/  |
#   | |      ___  _ __ | |_  | \  / |  __ _  _ __    __ _   __ _   ___  _ __
#   | |     / _ \| '__|| __| | |\/| | / _` || '_ \  / _` | / _` | / _ \| '__|
#   | |____|  __/| |   | |_  | |  | || (_| || | | || (_| || (_| ||  __/| |
#    \_____|\___||_|    \__| |_|  |_| \__,_||_| |_| \__,_| \__, | \___||_|
#                                                           __/ |
#                                                          |___/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/cert-manager/values.yaml
          - $argocd-self/overlays/seemscloud/values/cert-manager/values.yaml
    target:
      kind: Application
      name: cert-manager
##########################################################################################
#    _____       _    _          _______                 _
#   |_   _|     | |  (_)        |__   __|               (_)
#     | |   ___ | |_  _   ___      | | _ __  __ _   ___  _  _ __    __ _
#     | |  / __|| __|| | / _ \     | || '__|/ _` | / __|| || '_ \  / _` |
#    _| |_ \__ \| |_ | || (_) |    | || |  | (_| || (__ | || | | || (_| |
#   |_____||___/ \__||_| \___/     |_||_|   \__,_| \___||_||_| |_| \__, |
#                                                                   __/ |
#                                                                  |___/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-jaeger/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-jaeger/values.yaml
    target:
      kind: Application
      name: istio-jaeger
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-elasticsearch/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-elasticsearch/values.yaml
    target:
      kind: Application
      name: istio-elasticsearch
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-kibana/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-kibana/values.yaml
    target:
      kind: Application
      name: istio-kibana
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-kiali/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-kiali/values-1-17-1.yaml
      - op: replace
        path: /spec/sources/1/helm/releaseName
        value: kiali-1-17-1
      - op: replace
        path: /metadata/name
        value: istio-kiali-1-17-1
    target:
      kind: Application
      name: istio-kiali-green
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-kiali/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-kiali/values-1-17-2.yaml
      - op: replace
        path: /spec/sources/1/helm/releaseName
        value: kiali-1-17-2
      - op: replace
        path: /metadata/name
        value: istio-kiali-1-17-2
    target:
      kind: Application
      name: istio-kiali-blue
##########################################################################################
#    __  __        _          _  _       ____
#   |  \/  |      | |        | || |     |  _ \
#   | \  / |  ___ | |_  __ _ | || |     | |_) |
#   | |\/| | / _ \| __|/ _` || || |     |  _ <
#   | |  | ||  __/| |_| (_| || || |____ | |_) |
#   |_|  |_| \___| \__|\__,_||_||______||____/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/metallb/values.yaml
          - $argocd-self/overlays/seemscloud/values/metallb/values.yaml
    target:
      kind: Application
      name: metallb
##########################################################################################
#                                 __          __           _      __  _
#       /\                        \ \        / /          | |    / _|| |
#      /  \    _ __  __ _   ___    \ \  /\  / /___   _ __ | | __| |_ | |  ___ __      __ ___
#     / /\ \  | '__|/ _` | / _ \    \ \/  \/ // _ \ | '__|| |/ /|  _|| | / _ \\ \ /\ / // __|
#    / ____ \ | |  | (_| || (_) |    \  /\  /| (_) || |   |   < | |  | || (_) |\ V  V / \__ \
#   /_/    \_\|_|   \__, | \___/      \/  \/  \___/ |_|   |_|\_\|_|  |_| \___/  \_/\_/  |___/
#                    __/ |
#                   |___/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argo-events/values.yaml
          - $argocd-self/overlays/seemscloud/values/argo-events/values.yaml
    target:
      kind: Application
      name: argo-events
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argo-minio/values.yaml
          - $argocd-self/overlays/seemscloud/values/argo-minio/values.yaml
    target:
      kind: Application
      name: argo-minio
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argo-workflows/values.yaml
          - $argocd-self/overlays/seemscloud/values/argo-workflows/values.yaml
    target:
      kind: Application
      name: argo-workflows
##########################################################################################
#    _____       _    _          ____
#   |_   _|     | |  (_)        |  _ \
#     | |   ___ | |_  _   ___   | |_) |  __ _  ___   ___
#     | |  / __|| __|| | / _ \  |  _ <  / _` |/ __| / _ \
#    _| |_ \__ \| |_ | || (_) | | |_) || (_| |\__ \|  __/
#   |_____||___/ \__||_| \___/  |____/  \__,_||___/ \___|
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-base/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-base/values.yaml
    target:
      kind: Application
      name: istio-base
##########################################################################################
#    _____       _    _         _____
#   |_   _|     | |  (_)       |  __ \
#     | |   ___ | |_  _   ___  | |  | |
#     | |  / __|| __|| | / _ \ | |  | |
#    _| |_ \__ \| |_ | || (_) || |__| |
#   |_____||___/ \__||_| \___/ |_____/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-istiod/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-istiod/values-1-17-2.yaml
      - op: replace
        path: /spec/sources/1/targetRevision
        value: 1.17.2
      - op: replace
        path: /spec/sources/1/helm/releaseName
        value: istiod-1-17-2
      - op: replace
        path: /metadata/name
        value: istio-istiod-1-17-2
    target:
      kind: Application
      name: istio-istiod-blue
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-istiod/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-istiod/values-1-17-1.yaml
      - op: replace
        path: /spec/sources/1/targetRevision
        value: 1.17.1
      - op: replace
        path: /spec/sources/1/helm/releaseName
        value: istiod-1-17-1
      - op: replace
        path: /metadata/name
        value: istio-istiod-1-17-1
    target:
      kind: Application
      name: istio-istiod-green
##########################################################################################
#    _____       _    _          _____                                  _____         _
#   |_   _|     | |  (_)        |_   _|                                / ____|       | |
#     | |   ___ | |_  _   ___     | |   _ __    __ _  _ __  ___  ___  | |  __   __ _ | |_  ___ __      __ __ _  _   _
#     | |  / __|| __|| | / _ \    | |  | '_ \  / _` || '__|/ _ \/ __| | | |_ | / _` || __|/ _ \\ \ /\ / // _` || | | |
#    _| |_ \__ \| |_ | || (_) |  _| |_ | | | || (_| || |  |  __/\__ \ | |__| || (_| || |_|  __/ \ V  V /| (_| || |_| |
#   |_____||___/ \__||_| \___/  |_____||_| |_| \__, ||_|   \___||___/  \_____| \__,_| \__|\___|  \_/\_/  \__,_| \__, |
#                                               __/ |                                                            __/ |
#                                              |___/                                                            |___/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-ingress-gateway/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-ingress-gateway/values-1-17-2.yaml
      - op: replace
        path: /spec/sources/1/targetRevision
        value: 1.17.2
      - op: replace
        path: /spec/sources/1/helm/releaseName
        value: ingress-gateway-1-17-2
      - op: replace
        path: /metadata/name
        value: istio-ingress-gateway-1-17-2
    target:
      kind: Application
      name: istio-ingress-gateway-blue
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-ingress-gateway/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-ingress-gateway/values-1-17-1.yaml
      - op: replace
        path: /spec/sources/1/targetRevision
        value: 1.17.1
      - op: replace
        path: /spec/sources/1/helm/releaseName
        value: ingress-gateway-1-17-1
      - op: replace
        path: /metadata/name
        value: istio-ingress-gateway-1-17-1
    target:
      kind: Application
      name: istio-ingress-gateway-green
##########################################################################################
#    _  __          _
#   | |/ /         | |
#   | ' /  ___   __| |  __ _
#   |  <  / _ \ / _` | / _` |
#   | . \|  __/| (_| || (_| |
#   |_|\_\\___| \__,_| \__,_|
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/keda/values.yaml
          - $argocd-self/overlays/seemscloud/values/keda/values.yaml
    target:
      kind: Application
      name: keda
##########################################################################################
#    _                           _                  _____              _
#   | |                         (_)                / ____|            | |
#   | |      ___    __ _   __ _  _  _ __    __ _  | (___   _   _  ___ | |_  ___  _ __ ___
#   | |     / _ \  / _` | / _` || || '_ \  / _` |  \___ \ | | | |/ __|| __|/ _ \| '_ ` _ \
#   | |____| (_) || (_| || (_| || || | | || (_| |  ____) || |_| |\__ \| |_|  __/| | | | | |
#   |______|\___/  \__, | \__, ||_||_| |_| \__, | |_____/  \__, ||___/ \__|\___||_| |_| |_|
#                   __/ |  __/ |            __/ |           __/ |
#                  |___/  |___/            |___/           |___/
##########################################################################################
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/logging-redpanda/values.yaml
          - $argocd-self/overlays/seemscloud/values/logging-redpanda/values.yaml
    target:
      kind: Application
      name: logging-redpanda
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/logging-operator/values.yaml
          - $argocd-self/overlays/seemscloud/values/logging-operator/values.yaml
    target:
      kind: Application
      name: logging-operator
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/logging-operator-logging/values.yaml
          - $argocd-self/overlays/seemscloud/values/logging-operator-logging/values.yaml
    target:
      kind: Application
      name: logging-operator-logging