apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/argocd
  - ../../base/argocd-apps
  - ../../base/argocd-self
  - ../../base/prometheus
  - ../../base/cert-manager
  - ../../base/istio-jaeger

patches:
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argocd/values.yaml
          - $argocd-self/overlays/seemscloud/values/argocd/values.yaml
    target:
      kind: Application
      name: argocd
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argocd-apps/values.yaml
          - $argocd-self/overlays/seemscloud/values/argocd-apps/values.yaml
    target:
      kind: Application
      name: argocd-apps
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/prometheus/values.yaml
          - $argocd-self/overlays/seemscloud/values/prometheus/values.yaml
    target:
      kind: Application
      name: prometheus
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/cert-manager/values.yaml
          - $argocd-self/overlays/seemscloud/values/cert-manager/values.yaml
    target:
      kind: Application
      name: cert-manager
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-jaeger/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-jaeger/values.yaml
    target:
      kind: Application
      name: istio-jaeger