apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/generic
  - ../../base/stacks/argocd
  - ../../base/stacks/argo-workflows
  - ../../base/stacks/metrics
  - ../../base/stacks/istio
  - ../../base/stacks/queues
#  - ../../../base/keda
#  - ../../../base/crossplane