apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Base
  - ../../base/metallb
  - ../../base/cert-manager
  # Stacks
  - ../../base/stacks/argocd
  - ../../base/stacks/argo-workflows
  - ../../base/stacks/metrics
  - ../../base/stacks/istio
  - ../../base/stacks/queues
#  - ../../../base/keda
#  - ../../../base/crossplane