apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/argo-cd
  - ../../base/argocd-apps
  - ../../base/argo-self

patches:
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argo-self/overlays/seemscloud/values-argo-cd.yaml
    target:
      kind: Application
      name: argo-cd
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argo-self/base/argocd/values.yaml
          - $argo-self/overlays/seemscloud/values-argocd-apps.yaml
    target:
      kind: Application
      name: argocd-apps
