apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/argocd
  - ../../base/argocd-apps
  - ../../base/argocd-self
  - ../../base/metrics-prometheus
  - ../../base/metrics-grafana
  - ../../base/devops-cert-manager
  - ../../base/istio-jaeger
  - ../../base/istio-elasticsearch
  - ../../base/istio-kibana
  - ../../base/networking-metallb
  - ../../base/argo-events
  - ../../base/argo-minio
  - ../../base/argo-workflows

patches:
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argocd/values.yaml
          - $argocd-self/overlays/seemscloud/values/argocd/values.yaml
    target:
      kind: Application
      name: argocd
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argocd-apps/values.yaml
          - $argocd-self/overlays/seemscloud/values/argocd-apps/values.yaml
    target:
      kind: Application
      name: argocd-apps
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/metrics-prometheus/values.yaml
          - $argocd-self/overlays/seemscloud/values/metrics-prometheus/values.yaml
    target:
      kind: Application
      name: metrics-prometheus
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/metrics-grafana/values.yaml
          - $argocd-self/overlays/seemscloud/values/metrics-grafana/values.yaml
    target:
      kind: Application
      name: metrics-grafana
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/cert-manager/values.yaml
          - $argocd-self/overlays/seemscloud/values/cert-manager/values.yaml
    target:
      kind: Application
      name: cert-manager
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-jaeger/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-jaeger/values.yaml
    target:
      kind: Application
      name: istio-jaeger
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-elasticsearch/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-elasticsearch/values.yaml
    target:
      kind: Application
      name: istio-elasticsearch
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/istio-kibana/values.yaml
          - $argocd-self/overlays/seemscloud/values/istio-kibana/values.yaml
    target:
      kind: Application
      name: istio-kibana
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/metallb/values.yaml
          - $argocd-self/overlays/seemscloud/values/metallb/values.yaml
    target:
      kind: Application
      name: metallb
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argo-events/values.yaml
          - $argocd-self/overlays/seemscloud/values/argo-events/values.yaml
    target:
      kind: Application
      name: argo-events
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argo-minio/values.yaml
          - $argocd-self/overlays/seemscloud/values/argo-minio/values.yaml
    target:
      kind: Application
      name: argo-minio
  - patch: |-
      - op: add
        path: /spec/sources/1/helm/valueFiles
        value:
          - $argocd-self/base/argo-workflows/values.yaml
          - $argocd-self/overlays/seemscloud/values/argo-workflows/values.yaml
    target:
      kind: Application
      name: argo-workflows