apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - stacks/argocd
  - stacks/metrics
  - stacks/istio
  - stacks/argo-workflows
  - stacks/queues
  - ../../base/metallb
  - ../../base/cert-manager
  - others/