apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Generic
  - ../../base/generic
  # Stacks
  - ../../base/stacks/argocd
  #- ../../base/stacks/argo-workflows
  #- ../../base/stacks/metrics
  #- ../../base/stacks/istio
  # Tools
  #- ../../base/tools/keda
  #- ../../base/tools/crossplane
  #- ../../base/tools/kyverno
  # Queues
  - ../../base/queues/redpanda