apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd-system
spec:
  project: kyverno-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: kyverno
      repoURL: https://kyverno.github.io/kyverno/
      targetRevision: 3.0.5
      helm:
        releaseName: kyverno
        valueFiles:
          - $argocd-self/base/kyverno/values.yaml
