fullnameOverride: kiali-1-17-2

external_services:
  istio:
    component_status:
      components:
        - app_label: ingress-gateway-1-17-2
          is_core: true
          is_proxy: true
          namespace: istio-system
      enabled: true
    config_map_name: istio-1-17-2
    istio_sidecar_injector_config_map_name: istio-sidecar-injector-1-17-2
    istiod_deployment_name: istiod-1-17-2