fullnameOverride: redpanda

serviceAccount:
  create: true

statefulset:
  replicas: 3

storage:
  persistentVolume:
    enabled: false

external:
  enabled: false

resources:
  cpu:
    cores: 1

  memory:
    container:
      max: 2.5Gi

tls:
  enabled: false

console:
  enabled: true

  serviceAccount:
    create: true

  service:
    type: LoadBalancer

config:
  cluster:
    default_topic_replications: 3
    auto_create_topics_enabled: true
    default_topic_partitions: 50

  tunable:
    kafka_batch_max_bytes: 10485760
    delete_retention_ms: 3600000