fullnameOverride: redpanda

serviceAccount:
  create: true

statefulset:
  replicas: 3

storage:
  persistentVolume:
    enabled: false

external:
  enabled: false

resources:
  cpu:
    cores: 1

  memory:
    container:
      max: 2.5Gi

tls:
  enabled: false

console:
  enabled: true

  serviceAccount:
    create: true

  service:
    type: LoadBalancer

config:
  cluster:
    default_topic_replications: 3
    max.message.bytes: 10485760