apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-prometheus
  namespace: argocd-system
spec:
  project: metrics-system
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 19.0.1
      helm:
        releaseName: prometheus
        valueFiles:
          - $argocd-self/base/metrics-prometheus/values.yaml
