fullnameOverride: prometheus

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

server:
  persistentVolume:
    enabled: false
  service:
    servicePort: 8080
    type: LoadBalancer