apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd-system
spec:
  project: argocd-system
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  info:
    - name: argocd.seems.cloud/domain
      value: tools
    - name: argocd.seems.cloud/team
      value: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions: [ ]
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: argocd-apps
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 1.4.0
      helm:
        releaseName: argocd-apps
        valueFiles:
          - $argocd-self/base/argocd-apps/values.yaml