fullnameOverride: kiali-blue

external_services:
  istio:
    component_status:
      components:
        - app_label: istiod
          is_core: true
          is_proxy: true
          namespace: istio-system
        - app_label: ingress-gateway-blue
          is_core: true
          is_proxy: true
          namespace: istio-ingressgateway-blue-system
      enabled: true
    root_namespace: istio-system
    config_map_name: istio-blue
    istiod_deployment_name: istiod-blue
    istio_sidecar_injector_config_map_name: istio-sidecar-injector-blue
    istio_canary_revision:
      current: "blue"
      upgrade: "green"
  istio_labels:
    app_label_name: "seems.cloud/app"
    version_label_name: "seems.cloud/version"
    injection_label_name: "istio-injection"
    injection_label_rev: "istio.io/rev"