fullnameOverride: kiali

auth:
  strategy: anonymous

deployment:
  service_type: LoadBalancer

external_services:
  istio_canary_revision:
    current: "blue"
    upgrade: "green"
  istio:
    component_status:
      components:
        - app_label: istiod
          is_core: true
          is_proxy: true
          namespace: istio-system
        - app_label: ingress-gateway-blue
          is_core: true
          is_proxy: true
          namespace: istio-ingressgateway-blue-system
        - app_label: ingress-gateway-green
          is_core: true
          is_proxy: true
          namespace: istio-ingressgateway-green-system
      enabled: true
#    config_map_name: istio-blue
    istio_sidecar_injector_config_map_name: istio-sidecar-injector-blue
#    istiod_deployment_name: istiod

  grafana:
    enabled: true
    in_cluster_url: http://grafana.metrics-system:8080
  prometheus:
    enabled: true
    url: http://prometheus-server.metrics-system:8080

  tracing:
    enabled: true
    in_cluster_url: http://jaeger-query.istio-tracing-system:16685

istio_namespace: istio-system

kiali_feature_flags:
  istio_upgrade_action: true

server:
  port: 8080

login_token:
  signing_key: "gIz9tJxrKtaxV0SM"
