fullnameOverride: kiali-blue

external_services:
  istio:
    component_status:
      components:
        - app_label: istiod
          is_core: true
          is_proxy: true
          namespace: istio-system
        - app_label: ingress-gateway-blue
          is_core: true
          is_proxy: true
          namespace: istio-ingressgateway-blue-system
      enabled: true
    config_map_name: istio-blue