fullnameOverride: kiali-green

external_services:
  istio:
    component_status:
      components:
        - app_label: istiod
          is_core: true
          is_proxy: true
          namespace: istio-system
        - app_label: ingress-gateway-green
          is_core: true
          is_proxy: true
          namespace: istio-ingressgateway-green-system
      enabled: true
    config_map_name: istio-green
    istiod_deployment_name: istiod-green