apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-jaeger
  namespace: argocd-system
spec:
  project: istio-tracing-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-tracing-system
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: jaeger
      repoURL: https://jaegertracing.github.io/helm-charts
      targetRevision: 0.65.2
      helm:
        releaseName: jaeger
        valueFiles:
          - $argocd-self/base/istio-jaeger/values.yaml
