apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-redpanda-console
  namespace: argocd-system
spec:
  project: logging-system
  destination:
    server: https://kubernetes.default.svc
    namespace: logging-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: redpanda
      repoURL: https://charts.redpanda.com/
      targetRevision: 0.6.9
      helm:
        releaseName: redpanda-console
        valueFiles:
          - $argocd-self/base/logging-redpanda-console/values.yaml
