serviceAccount:
  create: true

service:
  type: LoadBalancer

console:
  config:
    kafka:
      brokers:
        - redpanda-0.redpanda:9093
        - redpanda-1.redpanda:9093
        - redpanda-2.redpanda:9093