projects:
  - name: argocd-system
    namespace: argocd-system
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    sourceRepos:
      - 'https://github.com/seemscloud/helm-argocd-self.git'
      - 'https://argoproj.github.io/argo-helm'
      - 'https://charts.bitnami.com/bitnami'
    destinations:
      - namespace: argocd-system
        name: "in-cluster"
        server: https://kubernetes.default.svc
      - namespace: metrics-system
        name: "in-cluster"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: metrics-system
    namespace: argocd-system
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    sourceRepos:
      - 'https://prometheus-community.github.io/helm-charts'
      - 'https://github.com/seemscloud/helm-argocd-self.git'
    destinations:
      - namespace: metrics-system
        name: "in-cluster"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'