apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd-system
spec:
  project: argocd-system
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  info:
    - name: argocd.seems.cloud/domain
      value: tools
    - name: argocd.seems.cloud/team
      value: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/seemscloud/helm-argocd-self.git
    targetRevision: main
    path: overlays/seemscloud