apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd-system
spec:
  project: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: [ ]
  source:
    repoURL: https://github.com/seemscloud/helm-argocd-self.git
    targetRevision: main
    path: overlays