fullnameOverride: argocd

configs:
  params:
    server.disable.auth: true
    server.insecure: true

  repositories:
    seemscloud-argo-self:
      url: https://github.com/seemscloud/helm-argocd-self.git
      name: "[SeemsCloud] Argo Self"
      type: git
      insecure: "true"
    argoproj:
      url: https://argoproj.github.io/argo-helm
      name: "[ArgoProj][Helm] Helm Charts"
      type: helm
      insecure: "true"
  clusterCredentials: []
#     - name: seemscloud
#       server: https://kubernetes.default.svc
#       config:
#         bearerToken: "<authentication token>"
#         tlsClientConfig:
#           insecure: false

server:
  replicas: 1

  service:
    type: LoadBalancer
    servicePortHttp: 8080
    servicePortHttps: 8443

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

controller:
  replicas: 1

redis:
  enabled: false

redis-ha:
  enabled: true

  replicas: 2

  haproxy:
    replicas: 2