fullnameOverride: elasticsearch

masterService: elasticsearch
nodeGroup: aio

replicas: 3
minimumMasterNodes: 3
maxUnavailable: 3

persistence:
  enabled: false

terminationGracePeriod: 0

service:
  type: LoadBalancer

extraEnvs:
  - name: xpack.security.enabled
    value: "false"