fullnameOverride: alertmanager

replicaCount: 1

serviceAccount:
  create: true

persistence:
  enabled: false

service:
  type: LoadBalancer
  port: 8080

configmapReload:
  enabled: true

config:
  enabled: true
  global:
    resolve_timeout: 1m

  templates:
    - '/etc/alertmanager/*.tmpl'

  receivers:
    - name: 'slack-seemscloud-notifications'
      slack_configs:
        - channel: '#notifications'
          api_url: 'https://hooks.slack.com/services/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'
          send_resolved: true
          text: "text"
          title: "Title"

  route:
    receiver: 'slack-seemscloud-notifications'
    routes:
      - receiver: 'slack-seemscloud-notifications'
        group_by:
          - 'namespace_name'
          - 'cluster_name'
          - 'severity'
        match:
          namespace_name: test