fullnameOverride: alertmanager

replicaCount: 1

serviceAccount:
  create: true

persistence:
  enabled: false

service:
  type: LoadBalancer
  extraPorts:
    - port: 8080

configmapReload:
  enabled: true