fullnameOverride: alertmanager

replicaCount: 1

serviceAccount:
  create: true

persistence:
  enabled: false

service:
  type: LoadBalancer
  port: 8080

configmapReload:
  enabled: true

config:
  enabled: true
  global:
    resolve_timeout: 1m
    slack_api_url: 'https://hooks.slack.com/services/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'

  templates:
    - '/etc/alertmanager/*.tmpl'

  receivers:
    - name: 'slack-notifications'
      slack_configs:
        - channel: '#notifications'
          send_resolved: true
          title: |-
            test
          text: >-
            test

  route:
    group_wait: 10s
    group_interval: 5m
    receiver: 'slack-notifications'
    repeat_interval: 3h