apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd-system
spec:
  project: cert-manager-system
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.12.3
      helm:
        releaseName: cert-manager
        valueFiles:
          - $argocd-self/base/cert-manager/values.yaml
