configs:
  repositories:
    seemscloud-app-argocd-self:
      url: https://github.com/seemscloud/helm-argocd-self.git
      name: "[SeemsCloud][App] Argo Self"
      type: git
      insecure: "true"
    argoproj-helm-helm-charts:
      url: https://argoproj.github.io/argo-helm
      name: "[Ext][ArgoProj] Helm Charts"
      type: helm
      insecure: "true"
    bitnami-helm-helm-charts:
      url: https://charts.bitnami.com/bitnami
      name: "[Ext][Bitnami] Helm Charts"
      type: helm
      insecure: "true"
    prometheus-community-helm-helm-charts:
      url: https://prometheus-community.github.io/helm-charts
      name: "[Ext][Prometheus Community] Helm Charts"
      type: helm
      insecure: "true"
    grafana-helm-helm-charts:
      url: https://grafana.github.io/helm-charts
      name: "[Ext][Grafana] Helm Charts"
      type: helm
      insecure: "true"