apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-fluent-bit
  namespace: argocd-system
spec:
  project: logging-system
  destination:
    server: https://kubernetes.default.svc
    namespace: logging-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: fluent-bit
      repoURL: https://fluent.github.io/helm-charts
      targetRevision: 0.40.0
      helm:
        releaseName: fluent-bit
        valueFiles:
          - $argocd-self/base/stacks/logging/fluent-bit/values.yaml