fullnameOverride: fluent-bit

rbac:
  create: true
  nodeAccess: true
  eventsAccess: true

serviceAccount:
  create: true

image:
  tag: 2.1.8-debug

hotReload:
  enabled: true
  image:
    repository: ghcr.io/jimmidyson/configmap-reload
    tag: v0.11.1


terminationGracePeriodSeconds: 1

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 100%

#serviceMonitor:
#  enabled: true
#  interval: 30s
#  scrapeTimeout: 10s

env:
  - name: CUSTOM_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: CUSTOM_NODE_ADDRESS
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: CUSTOM_AGENT_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name

tolerations:
  - effect: NoSchedule
    key: dedicated
    value: control-plane

volumeMounts:
  - name: config
    mountPath: /fluent-bit/etc/conf

daemonSetVolumes:
  - name: varlogfluentbit
    hostPath:
      path: /var/log/fluentbit
      type: DirectoryOrCreate
  - name: varlogcontainers
    hostPath:
      path: /var/log/containers
  - name: varlogpods
    hostPath:
      path: /var/log/pods

daemonSetVolumeMounts:
  - name: varlogfluentbit
    mountPath: /var/log/fluentbit
    readOnly: false
  - name: varlogcontainers
    mountPath: /var/log/containers
    readOnly: true
  - name: varlogpods
    mountPath: /var/log/pods
    readOnly: true

luaScripts:
  dedot.lua: |
    function dedot(tag, timestamp, record)
        if record["kubernetes"] == nil then
            return 0, 0, 0
        end
        dedot_keys(record["kubernetes"]["annotations"])
        dedot_keys(record["kubernetes"]["labels"])
        return 1, timestamp, record
    end

    function dedot_keys(map)
        if map == nil then
            return
        end
        local new_map = {}
        local changed_keys = {}
        for k, v in pairs(map) do
            local deslashed = string.gsub(k, "%/", "_")
            local dedash = string.gsub(deslashed, "%-", "_")
            local dedotted = string.gsub(dedash, "%.", "_")
            if dedotted ~= k then
                new_map[dedotted] = v
                changed_keys[k] = true
            end
        end
        for k in pairs(changed_keys) do
            map[k] = nil
        end
        for k, v in pairs(new_map) do
            map[k] = v
        end
    end

config:
  service: |
    [SERVICE]
        Daemon                        Off
        Flush                         5
        Grace                         10
        Log_Level                     info
        Parsers_File                  /fluent-bit/etc/parsers.conf
        Parsers_File                  /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server                   On
        HTTP_Listen                   0.0.0.0
        HTTP_Port                     2020
        Health_Check                  On
        HC_Errors_Count               5
        HC_Retry_Failure_Count        5
        HC_Period                     60

  inputs: |
    [INPUT]
        Name                          tail
        Path                          /var/log/containers/*.log
        multiline.parser              cri
        Tag                           kubernetes.*
        Buffer_Chunk_Size             128k
        Buffer_Max_Size               128k
        storage.type                  memory
        Mem_Buf_Limit                 512MB
        Skip_Long_Lines               Off
        DB                            /var/log/fluentbit/tail.db
        DB.sync                       normal
        DB.locking                    false
        DB.journal_mode               OFF

    [INPUT]
        Name                          node_exporter_metrics
        Tag                           node_metrics
        scrape_interval               2

  filters: |
    [FILTER]
        Name                          modify
        Match                         kubernetes.*
        Rename                        log message
        Hard_copy                     time @timestamp

    [FILTER]
        name                          multiline
        match                         kubernetes.*
        multiline.key_content         message
        mode                          partial_message
        emitter_mem_buf_limit         512MB

    [FILTER]
        Name                          kubernetes
        Buffer_Size                   0
        Kube_CA_File                  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Tag_Prefix               kubernetes.var.log.containers
        Kube_Token_File               /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Token_TTL                600
        Labels                        On
        Annotations                   Off
        Kube_URL                      https://kubernetes.default.svc:443
        Match                         kubernetes.*
        Merge_Log                     On
        Use_Kubelet                   Off

    [FILTER]
        Name                          record_modifier
        Match                         kubernetes.*
        Record                        kubernetes.node_name ${CUSTOM_NODE_NAME}
        Record                        kubernetes.node_address ${CUSTOM_NODE_ADDRESS}
        Record                        kubernetes.agent_name ${CUSTOM_AGENT_NAME}

    [FILTER]
        Name    lua
        Match   kubernetes.*
        script  /fluent-bit/scripts/dedot.lua
        call    dedot

  outputs: |
    [OUTPUT]
        Name                          kafka
        Match                         kubernetes.*
        Brokers                       redpanda.queues-system.svc:9093
        Topics                        logs
        Workers                       3
        rdkafka.compression.codec     gzip
        rdkafka.request.required.acks 1

    [OUTPUT]
        Name                          prometheus_exporter
        Match                         node_metrics
        Host                          0.0.0.0
        Port                          2021