apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-operator-logging
  namespace: argocd-system
spec:
  project: logging-system
  destination:
    server: https://kubernetes.default.svc
    namespace: logging-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud/helm-argocd-self.git
      targetRevision: main
      ref: argocd-self
    - chart: logging-operator-logging
      repoURL: https://kube-logging.github.io/helm-charts
      targetRevision: 4.2.2
      helm:
        releaseName: logging-operator-logging
        valueFiles:
          - $argocd-self/base/logging-operator-logging/values.yaml
