apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: components
  namespace: argocd-system
spec:
  project: components-system
  destination:
    server: https://kubernetes.default.svc
    namespace: components-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/seemscloud-trainings/helm-argocd-self-components.git
      ref: argocd-self
      path: overlays/seemscloud